name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: ":boom: Breaking changes"
    labels: 
      - breaking
  - title: 🚨 Removed
    label: removed
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 🚦 Tests
    labels:
      - test
      - tests
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: 📦 Dependency updates
    label: 'dependencies'
  - title: 📝 Documentation
    label: documentation
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
