name: Build and Push Container (Simple)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push container
    uses: hmcts/cnp-githubactions-library/workflows/container-build-and-push.yaml@main
    with:
      image-name: myapp  # Change this to your application name
    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
